#!/usr/bin/env node

/**
 * Interactive setup script for a new PDS deployment
 * Generates keys, creates DID, and writes configuration to .dev.vars
 */

import { Secp256k1Keypair } from '@atproto/crypto';
import { randomBytes } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as readline from 'node:readline/promises';

const __dirname = dirname(fileURLToPath(import.meta.url));

const rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout,
});

async function prompt(question) {
	return rl.question(question);
}

async function generateAuthToken() {
	return randomBytes(32).toString('base64url');
}

async function main() {
	console.log('🚀 PDS Setup\n');
	console.log('This script will generate keys and configuration for your PDS.\n');

	// Get hostname
	const hostname = await prompt('Enter your PDS hostname (e.g., pds.example.com): ');
	if (!hostname) {
		console.error('Error: Hostname is required');
		process.exit(1);
	}

	// Get handle
	const handle = await prompt(
		`Enter your handle (e.g., alice.${hostname}): `,
	);
	if (!handle) {
		console.error('Error: Handle is required');
		process.exit(1);
	}

	console.log('\n🔑 Generating secp256k1 keypair...');
	const keypair = await Secp256k1Keypair.create({ exportable: true });
	const privateKeyJwk = await keypair.export();
	const publicKeyMultibase = keypair.did();

	console.log('🆔 Creating DID...');
	const did = `did:web:${hostname}`;

	console.log('🎫 Generating auth token...');
	const authToken = await generateAuthToken();

	console.log('\n✅ Configuration generated!\n');

	// Build .dev.vars content
	const devVarsContent = `# Generated by setup-pds.js on ${new Date().toISOString()}

# Public hostname of your PDS
PDS_HOSTNAME=${hostname}

# Your account's DID
DID=${did}

# Your account's handle
HANDLE=${handle}

# Bearer token for write operations
AUTH_TOKEN=${authToken}

# Private key for signing commits (secp256k1 JWK)
SIGNING_KEY=${JSON.stringify(privateKeyJwk)}

# Public key for DID document (multibase encoded)
SIGNING_KEY_PUBLIC=${publicKeyMultibase}
`;

	// Determine output path (run from repo root or from demos/pds)
	const cwd = process.cwd();
	let outputPath;

	if (cwd.endsWith('demos/pds')) {
		outputPath = join(cwd, '.dev.vars');
	} else {
		outputPath = join(cwd, 'demos/pds/.dev.vars');
	}

	console.log(`📝 Writing configuration to ${outputPath}...\n`);
	await writeFile(outputPath, devVarsContent, 'utf-8');

	console.log('✨ Setup complete!\n');
	console.log('Next steps:');
	console.log('1. Create R2 bucket: wrangler r2 bucket create demo-pds-blobs');
	console.log('2. Run locally: pnpm run dev');
	console.log('3. Deploy to production:');
	console.log('   - Set secrets: wrangler secret put DID (repeat for each secret)');
	console.log('   - Deploy: pnpm run deploy\n');

	console.log('📋 Your configuration:');
	console.log(`   DID: ${did}`);
	console.log(`   Handle: ${handle}`);
	console.log(`   Hostname: ${hostname}`);
	console.log(`   Auth Token: ${authToken.substring(0, 12)}...`);
	console.log(`   Public Key: ${publicKeyMultibase}\n`);

	rl.close();
}

main().catch((err) => {
	console.error('Error:', err);
	process.exit(1);
});
